language: ruby

rvm:
  - 2.2.0

services: postgresql

before_script:
  - psql -c 'create database daysinturkey_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: B2FjyjOLP5/z+V/57TN10+WaEdWwniQb4sKRnUYdC1qOQIOH5nTDhT2S4k4AWMLOOWETw3LbEWc5JDQ19p06ovyUNHdn1kBngDKva1FMMQ2NkmQzVpR7oZ8BU2ZbssRVpJbQJxdt1VRIQRW/qnLIb/Crfa0NiS87Mbx1kFpt1Yg=
  app: daysinturkey-production
  on:
    repo: NoryDev/visacountdown
  run:
    - "rake db:migrate"
